alias l='ls -v --g'
alias L='ls -lhav --g'
alias ll='ls -lhv --g'
alias la='ls -av --g'
alias browse='nautilus .'
alias ping='ping -c 4'
alias sizeof='du -hs'
alias diskquota='df -h'
alias audio-reset='pulseaudio -k && sudo alsa reload'
alias net-reset='sudo modprobe -r ath9k && sudo modprobe ath9k'
alias myip='curl http://john-he.com/api/ip/'
alias server='python -m SimpleHTTPServer'

alias usd2cad='/home/johnhe00/scripts/usd2cad.sh'
alias open='/home/johnhe00/scripts/open.sh'
alias pdfmerge='/home/johnhe00/scripts/pdfmerge.sh'
alias calculator='python -i /home/johnhe00/scripts/calculator.py'
alias music='/home/johnhe00/scripts/music.sh'
